### PR TITLE
add fail2ban configuration to nextcloud doc

### PR DESCRIPTION
**Pull request by niko2**
I added a section in nextcloud documentation to update fail2ban log path.

Let me know if this is rather a bug with `yunohost app setting nextcloud datadir -v /media/storage` that would update fail2ban.

### CODE REVIEW

**Comment by OniriCorpe** [comment]
hi and thank you for your interest in improving documentation!

the app documentation here is deprecated, now apps must be documented in their respective repo in their `/doc` folder
for nextcloud it's here: https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/doc/

the docs about packaging documentation: https://yunohost.org/fr/packaging_app_doc

---

now for the fail2ban config, you don't need to edit it by hand, as the package already handles it:
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/install#L250-L251
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade#L362-L363

what is the purpose of this modification? are you in a specific configuration?

**Comment by niko2** [comment]
> hi and thank you for your interest in improving documentation!
> 
> the app documentation here is deprecated, now apps must be documented in their respective repo in their `/doc` folder for nextcloud it's here: https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/doc/
> 
> the docs about packaging documentation: https://yunohost.org/fr/packaging_app_doc
> 
> now for the fail2ban config, you don't need to edit it by hand, as the package already handles it: https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/install#L250-L251 https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade#L362-L363
> 
> what is the purpose of this modification? are you in a specific configuration?

Thank you for the links.
Yes, I use a specific folder for nextcloud storage.
Since I cannot choose it at installation time (perhaps I missed something ?), I changed it manually later.
How can I do it better ?

**Comment by OniriCorpe** [comment]
i think the most simple and convenient would be to edit the `data_dir` in the nextcloud package settings
so the package behaviour would remain the standard one, except your custom `data_dir` path will be respected during configuration regeneration at each package update

`data_dir` docs: https://yunohost.org/fr/packaging_apps_resources#data-dir

to see the actual `data_dir` path:
```bash
yunohost app setting nextcloud data_dir
/home/yunohost.app/nextcloud
```

to edit this setting:
```bash
yunohost app setting nextcloud data_dir -v /your/custom/data-path
```

you can document this process in the nexcloud package docs if you want

**Comment by OniriCorpe** [comment]
i close the issue since its irrelevant for this repo, but i'm still here if anything

**Pull request closed without merging**
