### PR TITLE
Adding use case YunoHost for non-profits organisations

### PR DESCRIPTION
**Pull request by yalh76**
Not sure :
* it's the good place to place the link to the new page
* if the name I choose for the page is OK

### CODE REVIEW

**Comment by yalh76** [comment]
> 
> 
> I think it's a great start. I have many comments but they can come in following PRs where we try to develop this document, no?
> 
> 🚀

It depends if there are a lot of changes to do ^^ would be less work for me if you do your own PRs ^^

**Comment by decentral1se** [comment]
> would be less work for me if you do your own PRs ^^

Yes, that was my idea. But someone has to review those too :)

**Comment by yalh76** [comment]
> 
> 
> Vraiment bien. Par contre, il serait utile de le traduire en fr. :-)

I agree to translate it into French because French is my mother tongue. But in a second time, when @ décentr1se will have done public relations and/or when the page will be almost definitive.

----

Je suis d'accord pour le traduire en français car le français est ma langue maternelle, mais dans un deuxième temps, lorsque @ décentr1se aura effectué ses relations publiques et/ou lorsque la page sera presque définitive.

**Comment by frju365** [comment]
Ok. Let's merge and see if we could improve it ! :-) Thanks !!

**Pull request merged**
