### PR TITLE
 Add commands to switch from Bind9 to dnsmasq

### PR DESCRIPTION
**Pull request by myrrhashad**
Just ran into this issue on a fresh install, had to search for the answer : could be worth mentioning directly ?

### CODE REVIEW

**Comment by alexAubin** [comment]
Hmmm yep we can maybe add the tip about `apt remove bind9` directly [here](https://github.com/YunoHost/install_script/blob/stretch/install_yunohost#L249) I think ? Possibly the same thing about apache ?

I think ideally I'd like to keep the install_manually.md page minimalist and avoid talking about technical edge-case to not scare users that won't run into it, but idk how other people feel about it

**Comment by myrrhashad** [comment]
Yeah, I think if this can be handled by the script then there's no need to change the documentation :)

**Comment by alexAubin** [comment]
@myrrhashad : So I implemented this in https://github.com/YunoHost/install_script/pull/58 , does it look okay to you ?

**Comment by alexAubin** [comment]
The other PR got merged so assuming the issue is fixed naow

**Pull request closed without merging**
