### PR TITLE
Add git documentation

### PR DESCRIPTION
**Pull request by maniackcrudelis**
Work done.

Can be merged whenever you want.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Tomorrow, if not too much support to do, I'll translate in French. (Or to be honest, deepl will translate for me :grin:)

**Comment by Plumf** [comment]
Hi, i create a git user helpers in this PR #1216 (sorry but for moment it's in french) this tutorial is for documentation but it looks pretty much the same as your document. A mutual document is possible ?

**Comment by maniackcrudelis** [comment]
Yeah, well as the title wasn't mentioning git, and because of the inclusive thing... I didn't read your PR.

Ok sorry, I tried, but I can't read your inclusive thing...

So, this doc is about git for packaging, and I will link it to the packaging section.
What your doc is about ?

**Comment by maniackcrudelis** [comment]
So... I'll merge in 3 days if no one as anything to says about it...

**Comment by Plumf** [comment]
Hi, i create an automatic translation without inclusive here : [DocuUseGit translate](https://pad.lqdn.fr/p/DocUseGit) . I think your document it's more complete. But my english it's not perfect ? Say me how thinks to my documents ?

**Comment by maniackcrudelis** [comment]
Your doc seems to be especially about the usage of git for the documentation. Mine is more "complete" but also a lot more tricky for people who do not code. And is about the usage of git when packaging, with some specifics part about it.
I think your contribution can be of great value to help people willing to contribute to the documentation, since it does use git.

I did some correction on your pad, feel free to use it or not.

**Comment by Plumf** [comment]
Thanks for the corrections I will use them for the English page. But indeed my documentation is for editors for documentation and not git in general. I didn't see or was indexing the page you wrote but I would probably refer to it. It seemed more complete to me even when read diagonally.

**Comment by Plumf** [comment]
I did some correction on your french page, question, I work locally. if i send commit you can accept or not ? or is it automatically integrated ? Your documentation is really understandable and simple. Thank for your work

**Comment by maniackcrudelis** [comment]
It depends on your permission on this repo.
The best to do though is to work on a separate branch (or fork) and to create a PR on my branch.

**Comment by Plumf** [comment]
I think it's okay, but I create an error with your previous commit, sorry.

**Pull request merged**
