### PR TITLE
Add high_quality and featured apps into the doc

### PR DESCRIPTION
**Pull request by maniackcrudelis**
Just a beginning to add high_quality apps and featured apps into the apps list into the doc.
Don't know if it work, don't know how to test.

And honestly, I'm not going to continue to work on that part.
I don't know Javascript and this fucking code isn't commented !!! I'm wasting my time just trying to understand how it's supposed to work.
So if some here know how to deal with that, it would be welcome. I don't, and I'm tired of having to struggle with non commented code.

### CODE REVIEW

**Comment by zamentur** [comment]
To test this you need to copy this page content into https://yunohost.org/#/apps/edit and click preview

**Comment by maniackcrudelis** [comment]
Thanks zamentur, unfortunately, as long as we don't have high quality apps or featured apps into our list, we can't really test it. But I hope it would happen soon.

**Comment by frju365** [comment]
We need a french version ? (I could do it if needed)

**Comment by alexAubin** [comment]
Superseded by https://github.com/YunoHost/doc/pull/1118 :s

**Pull request closed without merging**
