### PR TITLE
Update apps_wishlist.md

### PR DESCRIPTION
**Pull request by benjamindahl**
Added SOGo groupware

### CODE REVIEW

**Comment by M5oul** [comment]
This package works?

**Comment by benjamindahl** [comment]
Yes. Tested it today inside a VirtualBox environment.

  

cheers

  

Benny

  

  
\--  
Dipl.-Des. Benjamin Dahl  
Falckensteinstr. 15  
10997 Berlin  
Germany  
  
Phone: +49 (30) 83217244  
Mobile: +49 (176) 21300553  
  
Email: [post@bennyd.de](mailto:post@bennyd.de)  
Web:
[http://www.bennyd.de/](https://link.nylas.com/link/3cbdle43bbkux2v43oltmoomj
/local-
f0275bc6-cad3/0?redirect=http%3A%2F%2Fwww.bennyd.de%2F&r=cmVwbHkrMDAyOTJiMjg3MjM0OWY0MTJjYTQyNDMyNGQ1YTI1YTE4ODE2NGQ4ZThhYTEzMTliOTJjZjAwMDAwMDAxMTM3YTVhMTM5MmExNjljZTA5OTM0MzM4QHJlcGx5LmdpdGh1Yi5jb20=)

  

  



On Jun. 16 2016, at 2:14 pm, M5oul &lt;notifications@github.com&gt; wrote:  

> This package works?

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/YunoHost/doc/pull/381#issuecomment-226467691&r=cmVwbHkrMDAyOTJiMjg3MjM0OWY0MTJjYTQyNDMyNGQ1YTI1YTE4ODE2NGQ4ZThhYTEzMTliOTJjZjAwMDAwMDAxMTM3YTVhMTM5MmExNjljZTA5OTM0MzM4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/ACkrKFXaPa90a6dGEvUxoSyqU9jFFM7mks5qMT4TgaJpZM4I3UST&r=cmVwbHkrMDAyOTJiMjg3MjM0OWY0MTJjYTQyNDMyNGQ1YTI1YTE4ODE2NGQ4ZThhYTEzMTliOTJjZjAwMDAwMDAxMTM3YTVhMTM5MmExNjljZTA5OTM0MzM4QHJlcGx5LmdpdGh1Yi5jb20=).

**Comment by benjamindahl** [comment]
Yes. Tested it today inside a VirtualBox environment.

cheers

Benny

bildschirmfoto 2016-06-16 um 16 26 37
bildschirmfoto 2016-06-16 um 16 26 45

**Comment by M5oul** [comment]
Ok, so may be you want to add it on [Community list](https://github.com/YunoHost/apps/blob/master/community.json)?

**Comment by M5oul** [comment]
Done in https://github.com/YunoHost/apps/commit/038222a2d6bb073e3b26facffaac8032a4961b1a

**Pull request closed without merging**
