### PR TITLE
Adds framagit :)

### PR DESCRIPTION
**Pull request by pierreozoux**

### CODE REVIEW

**Comment by M5oul** [comment]
Duplicate of https://github.com/YunoHost/doc/pull/343.

**Comment by pierreozoux** [comment]
Thanks, but it was not a duplicate, one was for the french version, and one for the english version.

**Comment by M5oul** [comment]
Sorry, I [revert them](https://github.com/YunoHost/doc/compare/175aedfc5f31...8e78b5931038). 
Actually, moulinette can only manage GitHub repositories.
We hope support GitLabs and Gogs repositories.

**Comment by pierreozoux** [comment]
Arf, sorry didn't know :/

On 21-12-2015 13:15, M5oul wrote:
> Sorry, I [revert them](https://github.com/YunoHost/doc/compare/175aedfc5f31...8e78b5931038). 
> Actually, moulinette can only manage GitHub repositories.
> We hope support GitLabs and Gogs repositories.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/YunoHost/doc/pull/342#issuecomment-166303683
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by pierreozoux** [comment]
do like me, accept any kind :)
https://github.com/indiehosters/LibrePaaS/blob/master/utils/provision.sh#L171

On 21-12-2015 13:15, M5oul wrote:
> Sorry, I [revert them](https://github.com/YunoHost/doc/compare/175aedfc5f31...8e78b5931038). 
> Actually, moulinette can only manage GitHub repositories.
> We hope support GitLabs and Gogs repositories.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/YunoHost/doc/pull/342#issuecomment-166303683
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Pull request closed without merging**
