### PR TITLE
Adding Debian 8 in prerequisite in addition to Debian 7

### PR DESCRIPTION
**Pull request by paoesco**
Yunohost works on Debian 7 and Debian 8. Adding Debian 8 on pre requisite

### CODE REVIEW

**Comment by M5oul** [comment]
Done. Thanks.

**Comment by opi** [comment]
Why not ask for Debian Jessie (8) only for now ? I mean, it's current stable ;)

**Comment by M5oul** [comment]
We could recommend Jessy and say YunoHost also support Wheezy.

**Comment by opi** [comment]
you're right, let's do that !

( btw, repeat after me : jessie, jessie, jessie ... )

**Comment by M5oul** [comment]
In fact, I thought it was jessy in english!

**Comment by opi** [comment]
https://en.wikipedia.org/wiki/Jessie_%28Toy_Story%29

**Pull request closed without merging**
