### PR TITLE
Update apps_wishlist.md

### PR DESCRIPTION
**Pull request by Graninius**

### CODE REVIEW

**Comment by alexAubin** [comment]
I find it amazingly difficult to have the slightest idea what this project is even about ...

**Comment by ericgaspar** [comment]
I was thinking the same.

**Comment by Graninius** [comment]
Hm... It's absolutely easy to understand. In two words: it's much better than VPN because it uses ShadowsoksR to pass strongest firewalls (Great Wall in China etc.) to communicate the people in the World )
[https://www.youtube.com/watch?v=eoUx2QG8ngw&t=593s](url)
(use subs translated)

**Comment by ericgaspar** [comment]
Sorry but no, it's absolutely not easy to understand. The description doesn't make sense and the project documentation seems to be only in Chinese.
How do you expect contributors to invest time on packaging this?

**Comment by alexAubin** [comment]
(I legit thought it was a chat app after trying to translate the chinese stuff in google translate...)

**Comment by Graninius** [comment]
Yes, I agree with you, guys ) It's quite difficult  contributors to understand it (
There is some documentation in English https://github.com/XTLS/Xray-examples

**Pull request closed without merging**
