### PR TITLE
French version of Apps in Progress

### PR DESCRIPTION
**Pull request by chtixof**

### CODE REVIEW

**Comment by M5oul** [comment]
I've improved the french page of app in progress.
But I can not input the redirection towards apps_in_progress_fr in apps_fr.
For me, it more practice to be directly redirected to the list of apps in progress.
Here my changements: https://github.com/YunoHost/doc/commit/31acbb5a85c49a5d2e2080da3db4a1977e14458b & https://github.com/YunoHost/doc/commit/39d0220bf3c3f4b63cab3b5e1c569178bd00310d

**Comment by chtixof** [comment]
Hi M5oul. I tested the doc on line. It does not work as expected.

What we have:
from
https://yunohost.org/#/apps
having language set to French, click on Apps en cours
https://yunohost.org/#/apps_in_progress_en
English... click on Apps in Progress
https://yunohost.org/#/apps_in_progress
French... with a button on the bottom "Liste des apps en cours"
And so on click on the button Apps en cours/Apps in progress toggles languages the wrong way

What I would expect:
from
https://yunohost.org/#/apps
having language set to French, click on Apps en cours
https://yunohost.org/#/apps_in_progress
French... with a link in English at the bottom "Apps in Progress"
Click  on this link 
https://yunohost.org/#/apps_in_progress_en
English... click on Apps in Progress
stay on the same page, in English

Sorry. This is rather boring and seems difficult to get on working the way we want. If you want to go on, I can try to make it working, but in this case, I want to be able to test my changes. Is it worth to install the web doc app on my test server? In this case, how?

Cheers.

**Comment by M5oul** [comment]
I don't see what you really want.
I let you do an other pull request with what you want.
You could install [Simone](https://github.com/Kloadut/Simone) on your server to get what you expected.

**Comment by chtixof** [comment]
En voiture Simone ! Changes are now tested.

**Comment by chtixof** [comment]
Sorry for the possible misuse of Github. I still have to understand how it works... I don't understand why my previous comment closed this pull request. So I "Reopen and comment"...

**Comment by M5oul** [comment]
I added `apps_in_progress_fr` page: https://github.com/YunoHost/doc/commit/ebebe23d3e2cb2d8a8dd90e0d5b47be9affb1330

**Comment by M5oul** [comment]
I find damage that from `apps_fr` page to be redirected to french pages with a french web browser.
In my point of view, I prefer to be directly directed towards pages containing content, as it happens English pages.
What other guys think?

**Comment by chtixof** [comment]
Hello. Actually, we should change Simone: for a french browser, when page_fr.md does not exist, it should take page.md. I'll think about a pull request...

**Pull request closed without merging**
