### PR TITLE
I updated the link

### PR DESCRIPTION
**Pull request by MyNameIsTroll**
the link wasn't working

### CODE REVIEW

**Comment by alexAubin** [comment]
I don't understand, it works for me... If it doesn't, then that's a bug and probably doesn't affect just this link. Also we don't really want to point to github because the interface is different, and people can't easily contribute, etc.

**Comment by MyNameIsTroll** [comment]
Strange... I tried with Firefox and Edge and I get to a page 404.

github

**Comment by alexAubin** [comment]
That's because you're not supposed to browse the doc from github, you're supposed to browse is through yunohost.org.

For example: https://yunohost.org/#/apps_wishlist

**Comment by MyNameIsTroll** [comment]
Okay, thank you. 
I misunderstood, sorry ^^

**Pull request closed without merging**
