### PR TITLE
Apps list panel color

### PR DESCRIPTION
**Pull request by Psycojoker**
Suite de https://github.com/YunoHost/doc/pull/364, j'ai eu l'idée d'utiliser les couleurs des panels bootstrap pour encore plus différencier les sections (et j'ai pas conséquent viré le bouton).

Screenshot:

capture d ecran 2016-04-17 a 06 25 42

### CODE REVIEW

**Comment by M5oul** [comment]
Must be done for english page.

**Comment by Psycojoker** [comment]
I wanted to get feedback before considering doing this.

**Comment by M5oul** [comment]
It great and ok for me.
Thanks.

**Comment by Psycojoker** [comment]
Done for english version.

I've removed the green panel and just keep grey panel to avoid sending a too approval message following opi recommendations. I've also put the first warning in red.

**Comment by Psycojoker** [comment]
Hey :)

Is something missing for merging? I think I've made what you wanted but correct me if I'm wrong.

Cheers,

**Pull request merged**
