### PR TITLE
[enh] Add a lot of details about backup in fr page

### PR DESCRIPTION
**Pull request by zamentur**
- [x] EN translation needed
- [x] Split in several pages ^^

### CODE REVIEW

**Comment by tituspijean** [comment]
I can take care of the translation and split the pages (using the modular pages), but I need some guidance on where to split them. 😉

**Comment by zamentur** [comment]
Capture d’écran 2021-07-20 à 21 40 49-fullpage

**Comment by zamentur** [comment]
I will split and let you translate, thanks :)

**Comment by zamentur** [comment]
@tituspijean you can translate all backup pages (just a part for borgbackup that i didn't finish)

**Comment by zamentur** [comment]
Thanks @Khrys42 for translation

**Pull request merged**
