### PR TITLE
VirtualBox dev environment: english translation

### PR DESCRIPTION
**Pull request by vrubiolo**
This commit translates the formerly French-only 'development environment with
VirtualBox' documentation to english. The screen captures have been updated as
well.

### CODE REVIEW

**Comment by vrubiolo** [comment]
First PR on the project, hopefully everything is correct. Special thanks to Aleks for his quick help on IRC!

**Comment by vrubiolo** [comment]
Thanks for the approval @alexAubin ! I did test the way you mentioned, that is in edit mode of the wiki, with the URLs switched to point to my web_app and rendering was fine (both FR and US). Hopefully, that covers it.

**Comment by alexAubin** [comment]
Let's find out ;) (Might take up to a couple of hours for the change to be pulled by the doc)

Thanks again

**Comment by vrubiolo** [comment]
Working as expected on https://yunohost.org/#/packaging_apps_virtualbox_en

**Pull request merged**
