### PR TITLE
[enh] Update instructions for certificate installation

### PR DESCRIPTION
**Pull request by Psycojoker**
Screenshots of the admin interface for LE to improve https://github.com/YunoHost/doc/blob/images_for_le/certmanager.md

### CODE REVIEW

**Comment by M5oul** [comment]
Need to be integrated on certificate_* pages.

**Comment by alexAubin** [comment]
Working on this PR after a user on support got confused by the current content of certificate.md
Still need to 

- [ ] Add image for french (I have screenshots, need to process them)
- [ ] Add explanation for CLI
- [ ] Translate to english

**Comment by alexAubin** [comment]
Annnnd ready for reviews

**Comment by alexAubin** [comment]
Will merge in a few days

**Pull request merged**
