### PR TITLE
Add smartypants extension to enhance typography

### PR DESCRIPTION
**Pull request by tituspijean**
cf. https://github.com/YunoHost/doc/pull/1716

Adding `smartypants` extension beautifies and respects typography laws by using the curved apostrophes and quotation marks, and even offers to display French guillemets. Documentation has been updated accordingly.

- [ ] Backend task @tituspijean: install said extension.

### CODE REVIEW

**Comment by zamentur** [comment]
I don't see how it doesn't apply to other content than fr ?

**Comment by tituspijean** [comment]
It indeed does not discriminate between languages for now. However, per Wikipedia, both [apostrophes](https://en.wikipedia.org/wiki/Apostrophe#Typographic_form) and [quotation marks](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table) in English can be used with their curved, typographic version.

This PR does not specifically target French, even though the issue arose from the French translation. From the second link I see we may have issues with the German version. I could have a look into it, could be a simple `if` to apply somewhere in the code.

**Comment by Psycojoker** [comment]
idk if this correctly take care of avoiding reformating code snippets like in `<pre>` of `<codeblock>` tag, otherwise that could break a lot of command line that people cold copy paste (already experienced that)

tbh I find people forcing for The Right French Typography so annoying that I don't want to hear about it anymore but that's not a real argument.

**Comment by tituspijean** [comment]
> idk if this correctly take care of avoiding reformating code snippets like in `<pre>` or `<codeblock>` tag, otherwise that could break a lot of command line that people cold copy paste (already experienced that)

You can check it out on my test server (`ynh.pijean.ovh/fr/packaging_apps_arguments_format`). Code blocks are excluded (as stated in the doc of the extension).

> tbh I find people forcing for The Right French Typography so annoying that I don't want to hear about it anymore but that's not a real argument.

I hear you. I am merely proposing a lazy way of handling it, while maintaining our habits of using `'` and `"`.

**Comment by tituspijean** [comment]
The plugin clashes with the Shortcode-UI tabs extension. Do *not* merge.

**Pull request closed without merging**
