### PR TITLE
Update apps_wishlist.md with Torrents.csv

### PR DESCRIPTION
**Pull request by cnred-dev**
Search for torrents or files within torrents

### CODE REVIEW

**Review by tituspijean — COMMENTED** [review]
Note that the upstream license is unknown.

**Comment by ericgaspar** [comment]
It seems to be a fork of this repo: https://git.netflux.io/rob/torrents.csv/src/branch/master/LICENSE

**Comment by tituspijean** [comment]
@AlexioTROM, @cnred-dev , if you want to have this app added, can you ask the upstream maintainer to add a clear LICENSE to their project? :)

**Review by Plumf — APPROVED** [review]

**Comment by tituspijean** [comment]
The repo does not exist anymore?! 😕 
https://codeberg.org/heretic/torrents-csv-server

**Pull request closed without merging**
