### PR TITLE
Create contributordoc.de.md

### PR DESCRIPTION
**Pull request by ol-z**

### CODE REVIEW

**Comment by alexAubin** [comment]
Eeeh wokay but the format of that page changed yesterday following the migration to Grav .. the proposed page doesnt seem to match the new format, c.f. https://raw.githubusercontent.com/YunoHost/doc/master/pages/04.contribute/contributordoc.md :/

**Review by tituspijean — CHANGES_REQUESTED** [review]
Danke for your contribution! <3

Indeed we transitioned to Grav, which requires a bit of a format change and uses Markdown. Can you make your translation fit into the English version Aleks has referred to?

**Review by alexAubin — APPROVED** [review]
:+1:

**Comment by ol-z** [comment]
Are there still changes required? 
If it works, I would like to translate some more pages. 
But I'm not sure, if there are are still changes requested.

**Comment by alexAubin** [comment]
Nope (I was just maybe hoping Titus would give a review because he sounded like he was more knowledgeable than me about German but maybe not :P) Let's just merge what's already there ! Thanks and of course feel free to submit more PR !

**Comment by tituspijean** [comment]
Ooops I did not see the later commits. Good for me, obviously. :)

**Pull request merged**
