### PR TITLE
First commit to donation

### PR DESCRIPTION
**Pull request by yalh76**

### CODE REVIEW

**Comment by yalh76** [comment]
When PR merged, the budget page will be available at https://yunohost.org/#/donate

**Comment by frju365** [comment]
Perhaps wait for Aleks feedback. I don't know if it's finished completely.

**Comment by yalh76** [comment]
> 
> 
> Perhaps wait for Aleks feedback. I don't know if it's finished completely.

I hope @alexAubin will improve my trashy contribution ^^

**Comment by alexAubin** [comment]
Also reworked the bottom 'Donate' button in https://github.com/YunoHost/doc/pull/1100

**Pull request merged**
