### PR TITLE
Finland: Remove the duplicate message regarding Port 25

### PR DESCRIPTION
**Pull request by stdedos**
https://markdown-it.github.io/ has good rendering support for footnotes, if you wish to demo it (GFM does not)

### CODE REVIEW

**Comment by stdedos** [comment]
image

I guess you may have to upgrade your rendering software 😕 
You may have to revert if you mind "the ugliness".

**Comment by tituspijean** [comment]
Uh... so weird. I actually checked it out on my dev server because I was not sure these tags were working. :/

BTW, https://markdown-it.github.io/ is *not* the correct way to check if it will work in our documentation. Check https://yunohost.org/fr/write_documentation 😉

**Comment by stdedos** [comment]
> Uh... so weird. I actually checked it out on [my dev server](https://ynh.pijean.ovh/en/administrate/specific_use_cases/isp) because I was not sure these tags were working. :/

I don't understand what I'm supposed to read (or how to read the stacktrace).

> BTW, [markdown-it.github.io](https://markdown-it.github.io/) is _not_ the correct way to check if it will work in our documentation. Check [yunohost.org/write_documentation](https://yunohost.org/write_documentation) 😉

Weeell ... [markdown-it.github.io](https://markdown-it.github.io/) _renders_ Commonmark on-the-go. Add Markdown, get HTML preview - done!

For your suggestion ([yunohost.org/write_documentation](https://yunohost.org/write_documentation)), ...
I opened 15 pages, and dived through 4 domains, to end up with the knowledge that Grav (your interface) uses Markdown.pl.
That's _so_ obsolete. https://commonmark.org/ is the way to go since many years for Markdown (Github _also_ uses a Commonmark variation (GFM)). None of those (by default) contain support for footnotes (hence my https://markdown-it.github.io/ suggestion), but it could be plugged-in on a Commommark installation.

It's definitely not a fun or "very useful" project, but I'd suggest the Yunohost project to switch to a more structured standard ASAP.

**Comment by tituspijean** [comment]
> I don't understand what I'm supposed to read (or how to read the stacktrace).

I have just tried something on this dev server that broke everything, bad timing. :) It was merely to confirm that your footnote tags were working there, at least.

---

Regarding the remainder of your comment: I am only here for the fun, so... duely noted. 😛 On a more serious note, we had to make a major overhaul of the documentation backend recently, and Grav seemed to be the CMS that required us to alter minimally our original documentation files (it was still a massive work). I guess the team will be pretty much devastated if we swap backend *again* so soon.

Nevertheless, thanks for your contributions, they are much appreciated.

**Comment by stdedos** [comment]
> > I don't understand what I'm supposed to read (or how to read the stacktrace).
> 
> ~I have just tried something on this dev server that broke everything, bad timing. :) It was merely to confirm that your footnote tags were working there, at least.~ Fixed. 😉

Yeap! Now it looks more awesome on your dev server

> Regarding the remainder of your comment: I am only here for the fun, so... duely noted. 😛 On a more serious note, we had to make a major overhaul of the documentation backend recently, and Grav seemed to be the CMS that required us to alter minimally our original documentation files (it was still a massive work). I guess the team will be pretty much devastated if we swap backend _again_ so soon.
> 
> Nevertheless, thanks for your contributions, they are much appreciated.

FWIW, Grav looks very promising - flat, file-based CMS. Perfect.

But that Markdown.pl thorn can potentially sting - and that's a project that has started on 2014 (coincidentally, around the same time that Commonmark spec was publically available).
It's one of those things that's never a problem - until it is. Luckily, transition is not so problematic (https://github.blog/2017-03-14-a-formal-spec-for-github-markdown/), but that's a pitch for the Grav team I guess.

**Pull request merged**
