### PR TITLE
Pentest documentation

### PR DESCRIPTION
**Pull request by M5oul**
I added pentest links in security part of documentation.

That could show how secure is YunoHost and what have been done on it.

Are you ok to publicly display it?

### CODE REVIEW

**Comment by Psycojoker** [comment]
Sound good (but I'm not 100% sure about it).

Regarding security since this is the subject: we should publish our security@yunohost.org somewhere with it's pgp no? (And sign that part of the page using this key to prove its us).

@opi: since you have created this key, what's your opinion on that? ^

**Comment by M5oul** [comment]
We could wait for last part of pentest (Grey Box) before signing something.

**Comment by Psycojoker** [comment]
Hm why? This gpg key is a way for people to communicate to us in a secure way in which they know that we will be the only ones able to read what they've said, this is a secure way to send us a email saying "hey, here is a critical security vulnerability and how to fix it".

**Comment by M5oul** [comment]
I am talking about:
>(And sign that part of the page using this key to prove its us)

**Comment by Psycojoker** [comment]
> I am talking about:
>> (And sign that part of the page using this key to prove its us)

Hm, why should we wait for the end of the pentesting then? I'm not sure to guess the reason (as this is decorated from it, it's just a way to prove that we are the owners of this PGP key).

**Comment by M5oul** [comment]
Ah, I thought you were talking about signing `security*.md` pages with GPG key.

**Comment by Psycojoker** [comment]
Ah no, just the extract with the key ;)

**Pull request merged**
