### PR TITLE
Updated apps_wishlist.md (Fipamo)

### PR DESCRIPTION
**Pull request by unicmyce**
I have added **Fipamo** to the wishlist.

### CODE REVIEW

**Comment by ericgaspar** [comment]
This is already packaged. It needs to be tested because I can't remember if it is working.
https://github.com/YunoHost-Apps/fipamo_ynh

**Comment by unicmyce** [comment]
> This is already packaged. It needs to be tested because I can't remember if it is working. https://github.com/YunoHost-Apps/fipamo_ynh

is it safe to test it? because i see it's not even in the catalog.

**Comment by ericgaspar** [comment]
It will be part of the catalog soon: https://github.com/YunoHost/apps/pull/1439

I am just testing it.. it works but there is still some issues. It should be safe to install and remove.

```
sudo yunohost app install https://github.com/YunoHost-Apps/fipamo_ynh/
```
`yourdomain.tld/dashboard`to finish the post-install

**Comment by unicmyce** [comment]
> It will be part of the catalog soon: [YunoHost/apps#1439](https://github.com/YunoHost/apps/pull/1439)
> 
> I am just testing it.. it works but there is still some issues. It should be safe to install and remove.
> 
> ```
> sudo yunohost app install https://github.com/YunoHost-Apps/fipamo_ynh/
> ```
> 
> `yourdomain.tld/dashboard`to finish the post-install

should i report it if i encounter any issue or not since it's still in testing phase?

**Pull request closed without merging**
