### PR TITLE
Advanced packaging

### PR DESCRIPTION
**Pull request by yalh76**
- with some dedications to YunoHost Maintainers.
- maybe more frenglish than english

### CODE REVIEW

**Comment by yalh76** [comment]
@alexAubin and @zamentur and @maniackcrudelis 
Let me know if it can help of if I delete it .... (It was made during a drunk Partial unemployment....)

**Comment by alexAubin** [comment]
Uh I dunno, sounds somewhat legit to me, let's keep it ? xD

**Comment by maniackcrudelis** [comment]
I may share some personal scripts to upgrade my VM, and to easily change the domain of my clones.
And also a quick mount of shared directory to work directly from my packages directory.

It was just a quick look from my phone.
You may go to deeply to clean up your phrasing though ;)

**Comment by alexAubin** [comment]
Related: https://framapic.org/MHjBUqk0XcFP/IAXKoWB13HWG.jpg

**Comment by yalh76** [comment]
> 
> 
> Related: https://framapic.org/MHjBUqk0XcFP/IAXKoWB13HWG.jpg

As we say in french: MDR.
I'm so kikoulol

**Comment by yalh76** [comment]
> 
> 
> I may share some personal scripts to upgrade my VM, and to easily change the domain of my clones.
> And also a quick mount of shared directory to work directly from my packages directory.
> 
> It was just a quick look from my phone.
> You may go to deepl to clean up your phrasing though ;)

Feel free to add your personnal scripts. I didn't add all my ugly scripts...

It was just my steps from first package PR to multi-package maintainer. Hopping we can help them to go until core-dev ^^

**Comment by maniackcrudelis** [comment]
...github doesn't work as well on a phone and on a computer...

Anyway, sounds interesting, but I think you should just rewrite some parts , add links to other parts of the documentation, (Virtual Box, ynh-dev and so on).
But otherwise, I think it may be interesting to have that kind of documentation.

As I was saying in a comment that disappeared... You don't have to set a "real" dns for your virtual machine, you can simply use your hosts file.

Also, I don't think going to core dev should be seen as the apotheosis of contributing to YunoHost. We need people in all parts of YunoHost, core and other parts.

I would love to see that picture included into that doc :grin:

**Comment by maniackcrudelis** [comment]
Aside of my script to use ynh-dev into VirtualBox, which should be into my repo.
Here the scripts I use, I let you guys see if it can be interesting or not.

A script I use to upgrade my master VM (other are clones of the master)
```
#!/bin/bash

# printers
normal="\e[0m"
bold="\e[1m"
white="\e[97m"
blue="\e[34m"
echo_info()
{
	echo -e "[${bold}${blue}INFO${normal}] ${bold}${white}$1${normal}"
}

echo_info "### Update host"
sudo apt update
sudo apt dist-upgrade

sudo yunohost settings set security.password.user.strength -v -1
sudo yunohost settings set security.password.admin.strength -v -1

echo_info "### Update package_check"
( cd package_check; git pull)
echo_info "### Update LXC container"
package_check/sub_scripts/lxc_upgrade.sh

echo_info "### Clean hosts"
sudo apt autoclean
sudo apt autoremove

echo_info "### Fill free space with zero"
cat /dev/zero > zeros ; sync ; rm zeros

echo_info "### Run 'VBoxManage modifyhd --compact file.vdi' to reduce the size of this VM"
```

Another script, use to mount as shared directory my packaging directory into my VM. To not have to copy paste everything.
```
#!/bin/bash

shared_folder=my_directory

# printers
normal="\e[0m"
bold="\e[1m"
white="\e[97m"
blue="\e[34m"
echo_info()
{
	echo -e "[${bold}${blue}INFO${normal}] ${bold}${white}$1${normal}"
}

# Create the main directory for the mount
sudo mkdir -p "./$shared_folder"

# Mount ynh-dev directory from the host
echo_info "Mount shared directory $shared_folder"
sudo mount -o defaults -t vboxsf $shared_folder "./$shared_folder"
```

And finally, the script I used to quickly modify my cloned VM.
To spare my disk space, I upgrade only my master VM and then clone other VM from the first one.
```
#!/bin/bash

master_domain=domain1.fr
domainX=domain2.fr
master_ip=70
ipX=68


sudo yunohost --admin-password admin domain add $domainX
sudo yunohost --admin-password admin domain add sous.$domainX
sudo yunohost --admin-password admin tools maindomain -n $domainX
sudo yunohost --admin-password admin domain remove $master_domain
sudo yunohost --admin-password admin domain remove sous.$master_domain

sudo sed -i "s/address 192.168.1.$master_ip/address 192.168.1.${ipX}/" /etc/network/interfaces

sudo reboot
```

**Comment by Psycojoker** [comment]
Oupsi I've actually hijacked your page name I've just realized >.>

**Comment by Psycojoker** [comment]
Sowy :< https://yunohost.org/#/packaging_apps_advanced

**Comment by yalh76** [comment]
> 
> 
> Oupsi I've actually hijacked your page name I've just realized >.>

No pbs, I will switch it to packaging_apps_final_boss and integrate @maniackcrudelis features

**Comment by alexAubin** [comment]
So eh not sure what to do with this, is it ready to merge ?

**Comment by alexAubin** [comment]
Bumpitybump ? :s

**Comment by ericgaspar** [comment]
Shall we merge these great tips?

**Comment by yalh76** [comment]
Not ready for merging, I have to add several things from Maniack

**Comment by yalh76** [comment]
@alexAubin ready to be merged.
@tituspijean : just don't know how to add a link in the menu :/

**Comment by tituspijean** [comment]
@yalh76 It should be `git mv`ed into a numbered subdir of [`pages/04.contribute/04.packaging_apps/`](https://github.com/YunoHost/doc/tree/master/pages/04.contribute/04.packaging_apps) to be automagically displayed in the menu ;)

**Pull request merged**
